INSERT INTO BASE_PRICE
VALUES (1, 'YEARLY', 'BASIC', 39);
INSERT INTO BASE_PRICE
VALUES (2, 'CUSTOM', 'BASIC', 1.2);
INSERT INTO BASE_PRICE
VALUES (3, 'YEARLY', 'EXTENDED', 49);
INSERT INTO BASE_PRICE
VALUES (4, 'CUSTOM', 'EXTENDED', 1.8);
INSERT INTO BASE_PRICE
VALUES (5, 'YEARLY', 'EXTRA', 59);
INSERT INTO BASE_PRICE
VALUES (6, 'CUSTOM', 'EXTRA', 2.4);
