CREATE TABLE BASE_PRICE
(
    ID      IDENTITY PRIMARY KEY,
    VARIANT VARCHAR(255),
    TYPE    VARCHAR(255),
    PRICE   REAL
);

CREATE TABLE RESULT
(
    ID           IDENTITY PRIMARY KEY,
    VARIANT      VARCHAR(255),
    TYPE         VARCHAR(255),
    CANCELLATION BOOLEAN,
    SPORT        BOOLEAN,
    CREATED      DATETIME,
    PRICE        REAL,
    PERSONS      INTEGER,
    START_DATE   DATE,
    END_DATE     DATE
);




